channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=3.6
  - pigz 
  - parallel 
  - gawk
  - unzip
  - entrez-direct 
  - emboss
  - clustalw 
  - mustang 
  - ncbi-datasets-cli=13.42.2
  - jq
  - phyml
  - bioconvert
  - probcons
  - calysto_bash
