channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=3.6
  - r-tidyverse
  - r-esquisse
  - r-skimr
  - r-plotly
  - r-paletteer
  - r-patchwork
  - r-visdat
  - r-scales
  - r-mass
  - r-rcpp
  - bioconductor-biocinstaller
  - bioconductor-enhancedvolcano
  - bioconductor-deseq2
  - mamba
  - libgcc 
  - gnutls 
  - libuuid 
  - pandoc 
  - qt 
  - scipy 
  - ncurses 
  - readline 
  - git 
  - libgfortran 
  - pigz 
  - parallel 
  - gawk
  - unzip
  - biopython 
  - blast 
  - entrez-direct 
  - emboss
  - bioawk 
  - hmmer 
  - pfam_scan 
  - clustalw 
  - mustang 
  - fastqe 
  - ncbi-datasets-cli=13.42.2
  - jq
  - phyml
  - bioconvert
  - probcons
  - mrbayes
  - bash_kernel
  - calysto_bash
