#!/bin/bash
set -euxo pipefail

CONDA_DIR="/srv/conda/envs/notebook/"

# fix all perl executables to use the correct perl version
find $CONDA_DIR -name "*.pl" | parallel -q sed -i.bak 's|!/usr/bin/perl|!/usr/bin/env perl|' {}
